### PR TITLE
Move to new file structure

### PR DESCRIPTION
**Pull request by splodingsocks**
Move to the file structure suggested by @jeffmo in #4

### CODE REVIEW

**Comment by marudor** [comment]
Looks jut like I've understood the Proposal by @jeffmo

**Comment by magicpat** [comment]
It would be nice to also see a specific flow-version, not only `flow-all`... 
Also I am not 100% sure which versions of flow should be tried on the `flow-all` directory... how is that defined?

Other than that, looks really promising! I am hyped :raised_hands:

**Comment by splodingsocks** [comment]
@ryyppy I wasn't quite sure how we're going to manage having multiple versions of flow-bin. I figured we'd address that need as soon as someone wants to contribute a definition that only works on a specific version of flow.

**Comment by jeffmo** [comment]
This looks good!

> Also I am not 100% sure which versions of flow should be tested on the flow-all directory

I suppose the test runner should check against all of them to keep "-all" honest

> I wasn't quite sure how we're going to manage having multiple versions of flow-bin

I imagine it might be easier/faster for the runner to grab/use the [flow binaries](https://github.com/facebook/flow/releases) directly -- but I suppose if it's more convenient to have the runner do an ephemeral `npm install flow-bin@VERSION` for each test, that works too

**Comment by splodingsocks** [comment]
That would certainly work.

I think I'll merge this, and we can do that in a different branch.

**Pull request merged**
